// Mocks generated by Mockito 5.4.4 from annotations
// in assetwize/test/features/insurance/domain/usecases/add_insurance_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:assetwize/features/insurance/domain/entities/insurance.dart'
    as _i2;
import 'package:assetwize/features/insurance/domain/repositories/insurance_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInsurance_0 extends _i1.SmartFake implements _i2.Insurance {
  _FakeInsurance_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [InsuranceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInsuranceRepository extends _i1.Mock
    implements _i3.InsuranceRepository {
  MockInsuranceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Insurance>> getInsurances() => (super.noSuchMethod(
        Invocation.method(
          #getInsurances,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Insurance>>.value(<_i2.Insurance>[]),
      ) as _i4.Future<List<_i2.Insurance>>);

  @override
  _i4.Future<_i2.Insurance> getInsurance(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getInsurance,
          [id],
        ),
        returnValue: _i4.Future<_i2.Insurance>.value(_FakeInsurance_0(
          this,
          Invocation.method(
            #getInsurance,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Insurance>);

  @override
  _i4.Future<void> addInsurance(_i2.Insurance? insurance) =>
      (super.noSuchMethod(
        Invocation.method(
          #addInsurance,
          [insurance],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
