// Mocks generated by Mockito 5.4.4 from annotations
// in assetwize/test/features/insurance/presentation/bloc/insurance_detail_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:assetwize/features/insurance/domain/entities/insurance.dart'
    as _i3;
import 'package:assetwize/features/insurance/domain/repositories/insurance_repository.dart'
    as _i2;
import 'package:assetwize/features/insurance/domain/usecases/get_insurance_detail.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInsuranceRepository_0 extends _i1.SmartFake
    implements _i2.InsuranceRepository {
  _FakeInsuranceRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInsurance_1 extends _i1.SmartFake implements _i3.Insurance {
  _FakeInsurance_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetInsuranceDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetInsuranceDetail extends _i1.Mock
    implements _i4.GetInsuranceDetail {
  MockGetInsuranceDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.InsuranceRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeInsuranceRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.InsuranceRepository);

  @override
  _i5.Future<_i3.Insurance> call(String? id) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i5.Future<_i3.Insurance>.value(_FakeInsurance_1(
          this,
          Invocation.method(
            #call,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Insurance>);
}
