// Mocks generated by Mockito 5.4.4 from annotations
// in assetwize/test/features/search/domain/usecases/search_all_assets_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:assetwize/features/garage/domain/entities/garage.dart' as _i3;
import 'package:assetwize/features/garage/domain/repositories/garage_repository.dart'
    as _i8;
import 'package:assetwize/features/insurance/domain/entities/insurance.dart'
    as _i2;
import 'package:assetwize/features/insurance/domain/repositories/insurance_repository.dart'
    as _i6;
import 'package:assetwize/features/jewellery/domain/entities/jewellery.dart'
    as _i4;
import 'package:assetwize/features/jewellery/domain/repositories/jewellery_repository.dart'
    as _i9;
import 'package:assetwize/features/realty/domain/entities/realty.dart' as _i5;
import 'package:assetwize/features/realty/domain/repositories/realty_repository.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInsurance_0 extends _i1.SmartFake implements _i2.Insurance {
  _FakeInsurance_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGarage_1 extends _i1.SmartFake implements _i3.Garage {
  _FakeGarage_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJewellery_2 extends _i1.SmartFake implements _i4.Jewellery {
  _FakeJewellery_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealty_3 extends _i1.SmartFake implements _i5.Realty {
  _FakeRealty_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [InsuranceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInsuranceRepository extends _i1.Mock
    implements _i6.InsuranceRepository {
  MockInsuranceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i2.Insurance>> getInsurances() => (super.noSuchMethod(
        Invocation.method(
          #getInsurances,
          [],
        ),
        returnValue: _i7.Future<List<_i2.Insurance>>.value(<_i2.Insurance>[]),
      ) as _i7.Future<List<_i2.Insurance>>);

  @override
  _i7.Future<_i2.Insurance> getInsurance(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getInsurance,
          [id],
        ),
        returnValue: _i7.Future<_i2.Insurance>.value(_FakeInsurance_0(
          this,
          Invocation.method(
            #getInsurance,
            [id],
          ),
        )),
      ) as _i7.Future<_i2.Insurance>);

  @override
  _i7.Future<void> addInsurance(_i2.Insurance? insurance) =>
      (super.noSuchMethod(
        Invocation.method(
          #addInsurance,
          [insurance],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [GarageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGarageRepository extends _i1.Mock implements _i8.GarageRepository {
  MockGarageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i3.Garage>> getGarages() => (super.noSuchMethod(
        Invocation.method(
          #getGarages,
          [],
        ),
        returnValue: _i7.Future<List<_i3.Garage>>.value(<_i3.Garage>[]),
      ) as _i7.Future<List<_i3.Garage>>);

  @override
  _i7.Future<_i3.Garage> getGarage(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getGarage,
          [id],
        ),
        returnValue: _i7.Future<_i3.Garage>.value(_FakeGarage_1(
          this,
          Invocation.method(
            #getGarage,
            [id],
          ),
        )),
      ) as _i7.Future<_i3.Garage>);

  @override
  _i7.Future<void> addGarage(_i3.Garage? garage) => (super.noSuchMethod(
        Invocation.method(
          #addGarage,
          [garage],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteGarage(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteGarage,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [JewelleryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockJewelleryRepository extends _i1.Mock
    implements _i9.JewelleryRepository {
  MockJewelleryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i4.Jewellery>> getJewelleries() => (super.noSuchMethod(
        Invocation.method(
          #getJewelleries,
          [],
        ),
        returnValue: _i7.Future<List<_i4.Jewellery>>.value(<_i4.Jewellery>[]),
      ) as _i7.Future<List<_i4.Jewellery>>);

  @override
  _i7.Future<_i4.Jewellery> getJewellery(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getJewellery,
          [id],
        ),
        returnValue: _i7.Future<_i4.Jewellery>.value(_FakeJewellery_2(
          this,
          Invocation.method(
            #getJewellery,
            [id],
          ),
        )),
      ) as _i7.Future<_i4.Jewellery>);

  @override
  _i7.Future<void> addJewellery(_i4.Jewellery? jewellery) =>
      (super.noSuchMethod(
        Invocation.method(
          #addJewellery,
          [jewellery],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteJewellery(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteJewellery,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [RealtyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealtyRepository extends _i1.Mock implements _i10.RealtyRepository {
  MockRealtyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i5.Realty>> getRealties() => (super.noSuchMethod(
        Invocation.method(
          #getRealties,
          [],
        ),
        returnValue: _i7.Future<List<_i5.Realty>>.value(<_i5.Realty>[]),
      ) as _i7.Future<List<_i5.Realty>>);

  @override
  _i7.Future<_i5.Realty> getRealty(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getRealty,
          [id],
        ),
        returnValue: _i7.Future<_i5.Realty>.value(_FakeRealty_3(
          this,
          Invocation.method(
            #getRealty,
            [id],
          ),
        )),
      ) as _i7.Future<_i5.Realty>);

  @override
  _i7.Future<void> addRealty(_i5.Realty? realty) => (super.noSuchMethod(
        Invocation.method(
          #addRealty,
          [realty],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteRealty(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteRealty,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
