// Mocks generated by Mockito 5.4.4 from annotations
// in assetwize/test/features/jewellery/domain/usecases/get_jewellery_detail_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:assetwize/features/jewellery/domain/entities/jewellery.dart'
    as _i2;
import 'package:assetwize/features/jewellery/domain/repositories/jewellery_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeJewellery_0 extends _i1.SmartFake implements _i2.Jewellery {
  _FakeJewellery_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [JewelleryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockJewelleryRepository extends _i1.Mock
    implements _i3.JewelleryRepository {
  MockJewelleryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Jewellery>> getJewelleries() => (super.noSuchMethod(
        Invocation.method(
          #getJewelleries,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Jewellery>>.value(<_i2.Jewellery>[]),
      ) as _i4.Future<List<_i2.Jewellery>>);

  @override
  _i4.Future<_i2.Jewellery> getJewellery(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getJewellery,
          [id],
        ),
        returnValue: _i4.Future<_i2.Jewellery>.value(_FakeJewellery_0(
          this,
          Invocation.method(
            #getJewellery,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Jewellery>);

  @override
  _i4.Future<void> addJewellery(_i2.Jewellery? jewellery) =>
      (super.noSuchMethod(
        Invocation.method(
          #addJewellery,
          [jewellery],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteJewellery(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteJewellery,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
