// Mocks generated by Mockito 5.4.4 from annotations
// in assetwize/test/features/realty/domain/usecases/get_realties_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:assetwize/features/realty/domain/entities/realty.dart' as _i2;
import 'package:assetwize/features/realty/domain/repositories/realty_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRealty_0 extends _i1.SmartFake implements _i2.Realty {
  _FakeRealty_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RealtyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealtyRepository extends _i1.Mock implements _i3.RealtyRepository {
  MockRealtyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Realty>> getRealties() => (super.noSuchMethod(
        Invocation.method(
          #getRealties,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Realty>>.value(<_i2.Realty>[]),
      ) as _i4.Future<List<_i2.Realty>>);

  @override
  _i4.Future<_i2.Realty> getRealty(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getRealty,
          [id],
        ),
        returnValue: _i4.Future<_i2.Realty>.value(_FakeRealty_0(
          this,
          Invocation.method(
            #getRealty,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Realty>);

  @override
  _i4.Future<void> addRealty(_i2.Realty? realty) => (super.noSuchMethod(
        Invocation.method(
          #addRealty,
          [realty],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRealty(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteRealty,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
