// Mocks generated by Mockito 5.4.4 from annotations
// in assetwize/test/features/search/presentation/bloc/search_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:assetwize/features/garage/domain/repositories/garage_repository.dart'
    as _i3;
import 'package:assetwize/features/insurance/domain/repositories/insurance_repository.dart'
    as _i2;
import 'package:assetwize/features/jewellery/domain/repositories/jewellery_repository.dart'
    as _i4;
import 'package:assetwize/features/realty/domain/repositories/realty_repository.dart'
    as _i5;
import 'package:assetwize/features/search/domain/entities/search_result.dart'
    as _i8;
import 'package:assetwize/features/search/domain/usecases/search_all_assets.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInsuranceRepository_0 extends _i1.SmartFake
    implements _i2.InsuranceRepository {
  _FakeInsuranceRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGarageRepository_1 extends _i1.SmartFake
    implements _i3.GarageRepository {
  _FakeGarageRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJewelleryRepository_2 extends _i1.SmartFake
    implements _i4.JewelleryRepository {
  _FakeJewelleryRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtyRepository_3 extends _i1.SmartFake
    implements _i5.RealtyRepository {
  _FakeRealtyRepository_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SearchAllAssets].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchAllAssets extends _i1.Mock implements _i6.SearchAllAssets {
  MockSearchAllAssets() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.InsuranceRepository get insuranceRepository => (super.noSuchMethod(
        Invocation.getter(#insuranceRepository),
        returnValue: _FakeInsuranceRepository_0(
          this,
          Invocation.getter(#insuranceRepository),
        ),
      ) as _i2.InsuranceRepository);

  @override
  _i3.GarageRepository get garageRepository => (super.noSuchMethod(
        Invocation.getter(#garageRepository),
        returnValue: _FakeGarageRepository_1(
          this,
          Invocation.getter(#garageRepository),
        ),
      ) as _i3.GarageRepository);

  @override
  _i4.JewelleryRepository get jewelleryRepository => (super.noSuchMethod(
        Invocation.getter(#jewelleryRepository),
        returnValue: _FakeJewelleryRepository_2(
          this,
          Invocation.getter(#jewelleryRepository),
        ),
      ) as _i4.JewelleryRepository);

  @override
  _i5.RealtyRepository get realtyRepository => (super.noSuchMethod(
        Invocation.getter(#realtyRepository),
        returnValue: _FakeRealtyRepository_3(
          this,
          Invocation.getter(#realtyRepository),
        ),
      ) as _i5.RealtyRepository);

  @override
  _i7.Future<List<_i8.SearchResult>> call(String? query) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [query],
        ),
        returnValue:
            _i7.Future<List<_i8.SearchResult>>.value(<_i8.SearchResult>[]),
      ) as _i7.Future<List<_i8.SearchResult>>);
}
